import { Job, JobCardData } from "./job";

export const topCompaniesData = [
  {
    id: "1",
    name: "FPT Software",
    logo: "/company-logos/fpt.png",
    jobCount: 120,
    industry: "Software Development",
    location: "Hanoi, Vietnam",
    followerCount: 1000,
    isFollowing: false,
    newJobsToday: 5,
    description:
      "Vietnam's largest IT company specializing in software development and digital transformation.",
  },
  {
    id: "2",
    name: "VNG Corporation",
    logo: "/company-logos/vng.png",
    jobCount: 80,
    industry: "Internet Services",
    location: "Ho Chi Minh City, Vietnam",
    followerCount: 800,
    isFollowing: false,
    newJobsToday: 3,
    description: "Leading internet services company in Vietnam, known for Zalo and Zing MP3.",
  },
  {
    id: "3",
    name: "Tiki",
    logo: "/company-logos/tiki.png",
    jobCount: 50,
    industry: "E-commerce",
    location: "Ho Chi Minh City, Vietnam",
    followerCount: 600,
    isFollowing: false,
    newJobsToday: 2,
    description: "One of the largest e-commerce platforms in Vietnam.",
  },
  {
    id: "4",
    name: "Shopee",
    logo: "/company-logos/shopee.png",
    jobCount: 70,
    industry: "E-commerce",
    location: "Ho Chi Minh City, Vietnam",
    followerCount: 700,
    isFollowing: false,
    newJobsToday: 4,
    description: "Leading e-commerce platform in Southeast Asia.",
  },
  {
    id: "5",
    name: "Grab",
    logo: "/company-logos/grab.png",
    jobCount: 60,
    industry: "Transportation",
    location: "Ho Chi Minh City, Vietnam",
    followerCount: 900,
    isFollowing: false,
    newJobsToday: 1,
    description: "Southeast Asia's leading ride-hailing and food delivery platform.",
  },
];

export const jobsData = [
  {
    id: 1,
    company: "FPT Software",
    logo: "src/assets/images/fpt.png",
    title: "Senior Frontend Developer",
    salary: "$1,500 - $2,500",
    location: "Hanoi",
    time: "2 hours ago",
    skills: ["ReactJS", "TypeScript", "TailwindCSS"],
  },
  {
    id: 2,
    company: "VNG Corporation",
    logo: "/company-logos/vng.png",
    title: "Backend Engineer - Python",
    salary: "$1,800 - $3,000",
    location: "Ho Chi Minh City",
    time: "5 hours ago",
    skills: ["Python", "Django", "PostgreSQL"],
  },
  {
    id: 3,
    company: "Tiki",
    logo: "/company-logos/tiki.png",
    title: "DevOps Engineer",
    salary: "$2,000 - $3,500",
    location: "Remote",
    time: "1 day ago",
    skills: ["Docker", "Kubernetes", "AWS"],
  },
  {
    id: 4,
    company: "Shopee",
    logo: "src/assets/images/shopee.png",
    title: "Data Engineer",
    salary: "$1,500 - $2,800",
    location: "Ho Chi Minh City",
    time: "2 days ago",
    skills: ["Python", "Spark", "SQL"],
  },
  {
    id: 5,
    company: "Zalo",
    logo: "/company-logos/zalo.png",
    title: "Mobile Developer (iOS)",
    salary: "$1,700 - $2,700",
    location: "Ho Chi Minh City",
    time: "3 days ago",
    skills: ["Swift", "iOS", "UIKit"],
  },
  {
    id: 6,
    company: "Grab",
    logo: "/company-logos/grab.png",
    title: "QA Engineer",
    salary: "$1,200 - $2,200",
    location: "Hanoi",
    time: "3 days ago",
    skills: ["Selenium", "Cypress", "Automation"],
  },
  {
    id: 7,
    company: "NashTech",
    logo: "/company-logos/nashtech.png",
    title: "Solution Architect",
    salary: "$3,000 - $5,000",
    location: "Ho Chi Minh City",
    time: "4 days ago",
    skills: ["AWS", "Microservices", "System Design"],
  },
  {
    id: 8,
    company: "Sendo",
    logo: "/company-logos/sendo.png",
    title: "UI/UX Designer",
    salary: "$1,300 - $2,300",
    location: "Ho Chi Minh City",
    time: "5 days ago",
    skills: ["Figma", "Adobe XD", "UI Design"],
  },
];

// Dữ liệu mẫu cho trang
export const sampleJobs: JobCardData[] = [
  {
    id: 1,
    company: "FPT Software",
    logo: "/company-logos/fpt.png",
    title: "Senior React Developer",
    salary: "25.000.000 - 35.000.000",
    location: "Hanoi",
    time: "1 day ago",
    skills: ["React", "TypeScript", "NodeJS"],
  },
  {
    id: 2,
    company: "VNG Corporation",
    logo: "/company-logos/vng.png",
    title: "DevOps Engineer",
    salary: "20.000.000 - 30.000.000",
    location: "HCM",
    time: "2 days ago",
    skills: ["Docker", "Kubernetes", "AWS"],
  },
  {
    id: 3,
    company: "Shopee",
    logo: "/company-logos/shopee.png",
    title: "Frontend Developer",
    salary: "18.000.000 - 25.000.000",
    location: "HCM",
    time: "3 days ago",
    skills: ["JavaScript", "React", "CSS"],
  },
  {
    id: 4,
    company: "Tiki",
    logo: "/company-logos/tiki.png",
    title: "Product Manager",
    salary: "20.000.000 - 30.000.000",
    location: "HCM",
    time: "4 days ago",
    skills: ["Agile", "Scrum", "Product Development"],
  },
  {
    id: 5,
    company: "Momo",
    logo: "/company-logos/momo.png",
    title: "Backend Engineer",
    salary: "22.000.000 - 32.000.000",
    location: "HCM",
    time: "2 days ago",
    skills: ["Java", "Spring Boot", "Microservices"],
  },
  {
    id: 6,
    company: "VNPAY",
    logo: "/company-logos/vnpay.png",
    title: "Data Engineer",
    salary: "20.000.000 - 28.000.000",
    location: "Hanoi",
    time: "3 days ago",
    skills: ["Python", "SQL", "Data Pipeline"],
  },
  {
    id: 7,
    company: "Microsoft",
    logo: "/company-logos/microsoft.png",
    title: "Software Engineer",
    salary: "30.000.000 - 45.000.000",
    location: "HCM",
    time: "1 week ago",
    skills: ["C#", ".NET", "Azure"],
  },
  {
    id: 8,
    company: "Amazon",
    logo: "/company-logos/amazon.png",
    title: "Data Scientist",
    salary: "35.000.000 - 50.000.000",
    location: "Remote",
    time: "5 days ago",
    skills: ["Python", "Machine Learning", "AWS"],
  },
  {
    id: 9,
    company: "Google",
    logo: "/company-logos/google.png",
    title: "UX/UI Designer",
    salary: "28.000.000 - 40.000.000",
    location: "HCM",
    time: "2 weeks ago",
    skills: ["Figma", "Adobe XD", "User Research"],
  },
  {
    id: 10,
    company: "Grab",
    logo: "/company-logos/grab.png",
    title: "Mobile Developer",
    salary: "25.000.000 - 38.000.000",
    location: "Hanoi",
    time: "6 days ago",
    skills: ["Flutter", "React Native", "iOS/Android"],
  },
  {
    id: 11,
    company: "Agoda",
    logo: "/company-logos/agoda.png",
    title: "QA Engineer",
    salary: "18.000.000 - 28.000.000",
    location: "HCM",
    time: "1 week ago",
    skills: ["Selenium", "TestNG", "Automation"],
  },
  {
    id: 12,
    company: "Netflix",
    logo: "/company-logos/netflix.png",
    title: "Backend Developer",
    salary: "32.000.000 - 46.000.000",
    location: "Remote",
    time: "3 days ago",
    skills: ["Java", "Spring Boot", "Microservices"],
  },
];

// Mẫu dữ liệu (sau này sẽ được lấy từ API)
export const jobsDataDetail: Job[] = [
  {
    id: 1,
    company: "FPT Software",
    logo: "/company-logos/fpt.png",
    title: "Senior React Developer",
    salary: "$2,500 - $3,500",
    location: "Hanoi",
    time: "1 day ago",
    skills: ["React", "TypeScript", "NodeJS"],
    experience: "3-5 years",
    level: "Senior",
    contractType: "Full-time",
    interviewProcess: ["Phone interview", "Technical interview", "Contract proposal"],
    responsibilities: [
      "Develop and maintain web applications using React, Redux, and TypeScript",
      "Collaborate with the backend team to integrate APIs and optimize performance",
      "Design and implement technical solutions that meet business requirements",
      "Develop and maintain frontend architecture, ensuring scalability and maintainability",
      "Work in an Agile/Scrum environment",
    ],
    basicRequirements: [
      "3-5 years of experience with React and modern frontend technologies",
      "Proficient in JavaScript/TypeScript, HTML5, CSS3",
      "Deep understanding of React Hooks, Redux, and state management",
      "Experience with RESTful APIs and GraphQL",
      "Knowledge of web performance optimization best practices",
    ],
    preferredSkills: [
      "Experience with Next.js, Gatsby, or other React frameworks",
      "Knowledge of testing with Jest, React Testing Library, and Cypress",
      "Experience with CI/CD pipelines",
      "Experience with UI libraries like Material-UI, Ant Design, or Tailwind CSS",
      "Excellent communication skills in English",
    ],
    benefits: [
      "Competitive salary and performance-based rewards",
      "Comprehensive health insurance for employees and their families",
      "Flexible work schedule and remote work policy",
      "International, dynamic work environment",
      "Continuous professional development training",
      "Team building activities and company events",
    ],
    companyDescription:
      "FPT Software is a leading IT company in Vietnam, specializing in providing software services and solutions to global customers.",
  },
  {
    id: 2,
    company: "VNG Corporation",
    logo: "/company-logos/vng.png",
    title: "DevOps Engineer",
    salary: "$2,000 - $3,000",
    location: "Ho Chi Minh City",
    time: "2 days ago",
    skills: ["Docker", "Kubernetes", "AWS"],
    experience: "2-4 years",
    level: "Middle",
    contractType: "Full-time",
    interviewProcess: ["Phone interview", "Technical interview", "Contract proposal"],
    responsibilities: [
      "Design and implement CI/CD solutions",
      "Manage and optimize systems on AWS and Kubernetes",
      "Automate software development processes",
      "Monitor and ensure system availability",
      "Build internal tools to improve development processes",
    ],
    basicRequirements: [
      "2-4 years of experience with DevOps and Cloud Infrastructure",
      "Experience with Docker, Kubernetes, and container orchestration",
      "Proficient in AWS and other cloud services",
      "Experience with CI/CD tools like Jenkins, GitLab CI, GitHub Actions",
      "Strong knowledge of networking, security, and monitoring",
    ],
    preferredSkills: [
      "Certifications in AWS, Google Cloud, or Azure",
      "Experience with IaC using Terraform or CloudFormation",
      "Experience with ELK stack or other logging/monitoring solutions",
      "Knowledge of microservices and cloud-native architecture",
      "Scripting skills with Python, Bash, or Go",
    ],
    benefits: [
      "Modern and dynamic work environment",
      "Opportunities to learn and grow in the latest technology field",
      "Attractive salary and regular performance evaluations",
      "Health insurance and other benefits",
      "Team building activities and company events",
      "Flexible work schedule and remote work policy",
    ],
    companyDescription:
      "VNG is one of the leading internet and technology companies in Vietnam, with a thriving ecosystem of technology products and digital services with millions of users.",
  },
];

// Mẫu dữ liệu công việc mới nhất
export const latestJobs: JobCardData[] = [
  {
    id: 3,
    company: "Shopee",
    logo: "/company-logos/shopee.png",
    title: "Frontend Developer",
    salary: "$1,800 - $2,500",
    location: "Ho Chi Minh City",
    time: "3 days ago",
    skills: ["JavaScript", "React", "CSS"],
  },
  {
    id: 4,
    company: "Tiki",
    logo: "/company-logos/tiki.png",
    title: "Product Manager",
    salary: "$2,000 - $3,000",
    location: "Ho Chi Minh City",
    time: "4 days ago",
    skills: ["Agile", "Scrum", "Product Development"],
  },
  {
    id: 5,
    company: "Momo",
    logo: "/company-logos/momo.png",
    title: "Backend Engineer",
    salary: "$2,200 - $3,200",
    location: "Ho Chi Minh City",
    time: "2 days ago",
    skills: ["Java", "Spring Boot", "Microservices"],
  },
  {
    id: 6,
    company: "VNPAY",
    logo: "/company-logos/vnpay.png",
    title: "Data Engineer",
    salary: "$2,000 - $2,800",
    location: "Hanoi",
    time: "3 days ago",
    skills: ["Python", "SQL", "Data Pipeline"],
  },
];

export const mockCompanyData = {
  id: "1",
  name: "Google",
  logo: "/company-logos/google.png",
  jobCount: 500,
  newJobsToday: 25,
  description: `Google is a global technology leader focused on improving the ways people connect with information. Google's innovations in web search and advertising have made its website one of the most viewed Internet destinations and its brand one of the most recognized in the world. Google's mission is to organize the world's information and make it universally accessible and useful.

Google's commitment to innovation and its core values has helped it maintain its position as one of the world's most influential companies. The company continues to develop new products and services that leverage its powerful technology and reach to provide users with increasingly useful, relevant, and innovative ways to connect with information.

At Google, engineers and scientists from diverse backgrounds come together to create technology that helps billions of people around the world. The company's culture encourages innovation, creativity, and collaboration, making it an ideal place for talented individuals to grow and make an impact.`,
  industry: "Technology",
  size: "100,000+ employees",
  founded: "1998",
  type: "Public",
  website: "https://google.com",
  email: "careers@google.com",
  phone: "+1 650-253-0000",
  address: "1600 Amphitheatre Parkway, Mountain View, CA 94043",
  socialMedia: {
    linkedin: "https://linkedin.com/company/google",
    facebook: "https://facebook.com/google",
    twitter: "https://twitter.com/google",
  },
  location: "Multiple locations",
  followerCount: 2500000,
  isFollowing: false,
  openPositions: 350,
};
